
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atptbcdwtfbbboimgzur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cHRiY2R3dGZiYmJvaW1nenVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTM1NDAsImV4cCI6MjA1NzQyOTU0MH0.2g_e2-GMvzXbdJJhQPoEiovUrbx0Y1d31TCkBwLjz-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
